# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 536e3d1e8e11bd770605ce6b861b6299f45af05cf595888ce1b67584098de33966948ac275b1925643e730bfdc105fcf2f388eea58b983ac78464154a3754f64
  default_url: 'http://localhost:3001'
  confirm_redirect: 'http://localhost:3000/#/login'
  client_url: 'http://localhost:3000/#/'
  confirm_route: 'http://localhost:3001/api/v1/users/confirm?confirmation_token='
  sendgrid_api: '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'
  blockio_btc_key: '11a8-4fdd-b757-e8f0'
  blockio_ltc_key: '9834-9dac-9ba6-b59f'
  expiration_session: 20000
  master_password: '144211'
  aws_access_key_id: AKIAIBU3UKV37OGMZ2LA
  aws_secret_access_key: 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
  aws_bucket_name:  llevatelo-develop

test:
  secret_key_base: 8ca9637c158e39c9bf1d16dc2efeaf07c6abb9d8899b49f779e6a16e22585f2002c2c55a4bdb1b9c699809d89733cbb38ca975e069b8af23a03512abdd263989

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: bb11cc055a8ba55931737f068e21d60cca3ce1b1c9af7b5a4ef037792c001245c775a736df73a3386f14f699971af740ba601c02f020dc58816fa93522968b11
  default_url: 'http://api.cryptobusinesscompany.com'
  confirm_redirect: 'http://app.cryptobusinesscompany.com/#/login'
  client_url: 'http://app.cryptobusinesscompany.com/#/'
  confirm_route: 'http://api.cryptobusinesscompany.com/api/v1/users/confirm?confirmation_token='
  sendgrid_api: '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'
  blockio_btc_key: 'fdfe-a5a2-5ce3-1f5f'
  blockio_ltc_key: 'e2c2-7773-7cbc-671d'
  expiration_session: 60
  master_password: '144211'
  aws_access_key_id: AKIAIBU3UKV37OGMZ2LA
  aws_secret_access_key: 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
  aws_bucket_name:  llevatelo-develop
